name: Actions Workflow
# schedule:
#   - cron: "1 * * * *"
on:
  push:
    branches:
      - master
      - staging
      - 'feature/*' # matches feature/a, feat/B etc.
    # paths:
    # - '**.js'
  pull:
    branches:
      - master
    types: [closed, assigned, opened, reopened]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls
      - name: Git Checkout
        uses: actions/checkout@v1
      - name: List files After Checkout
        run: |
          pwd
          ls
      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Rishabh
      - name: Log Greeting Time
        run: echo "${{steps.greet.outputs.time}}"
